version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
  app:
    depends_on:
      - mongodb
    restart: on-failure
    image: amazon-agency
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri": "mongodb://admin:password@mongodb:27017/test",
          "spring.data.mongodb.authentication-database":"admin",
          "jwt.expiration": "${JWT_EXPIRATION_TIME}",
          "jwt.secret": "${JWT_SECRET}",
          "server.servlet.context-path": "/api"
      }'
      _TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
